version: '3.7'
services:
  local-database:
    image: neo4j:latest
    ports:
      - '7474:7474'
      - '7687:7687'
    expose:
      - 7474
      - 7687
    volumes: -neo4j-data:/data

volumes:
  ne4j-data:
